version: "3"

services:
  database:
    restart: unless-stopped
    image: postgres:15
    container_name: database
    volumes:
      - ~/.pg/pg_data/emphasoft-tt:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"