# Generated by Django 5.0.3 on 2024-03-31 00:53

import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0002_remove_reservation_is_reserved_room_is_reserved"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservation",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="ended_at",
        ),
        migrations.RemoveField(
            model_name="room",
            name="is_reserved",
        ),
        migrations.AddField(
            model_name="reservation",
            name="end_date",
            field=models.DateField(default=timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="reservation",
            name="start_date",
            field=models.DateField(default=timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="reservation",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservations",
                to="reservation.room",
            ),
        ),
    ]
