name: Docker-compose test

on:
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Change directory to backend
        run: cd backend
      - name: Copy env
        run: cp .env.example .env
      - name: show files
        run: ls -la
      - name: Build the stack
        run: docker-compose -f docker-compose.yml up -d --build
 
